name: Build and Push Podman Image

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


          #- name: Set up Podman
          #uses: redhat-actions/podman-login@v1

      - name: Build and push image
        run: |
          podman build -t debian-cockpit:bookworm .
          #podman push debian-cockpit:bookworm
          #env:
          # Use secrets for authentication
          # DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          # DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          # DOCKER_REGISTRY: docker.io

      - name: Clean up
        run: |
          podman image prune -a -f
